language: python
python:
  - "3.8"
  - "3.9"

install:
  - pip install requests
  - pip install codecov
  - pip install coveralls
  - pip install pytest pytest-cov

script:
  - python setup.py install
  - pytest --cov=vtapi3

after_success:
  - codecov
  - coveralls
